language: node_js

sudo: false

node_js:
  - "6"

cache:
  apt: true
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  ssh_known_hosts:
      - github.com
      - git.coding.net
      - 118.193.213.247

before_script:
  - echo -e 'Host 118.193.213.247\n\tStrictHostKeyChecking no\n' >> ~/.ssh/config
  - ssh-keyscan -H -t rsa,dsa git.coding.net >> ~/.ssh/known_hosts
  - ssh-keyscan -H -t rsa,dsa -p 21521 118.193.213.247 >> ~/.ssh/known_hosts
  - curl "https://api.keycdn.com/zones/purgeurl/$CDN_ZONE_ID.json" -u $CDN_API: -X DELETE -H "Content-Type: application/json" --data '{"urls":["$CDN_ZONE_URL/index.html","$CDN_ZONE_URL/tags/index.html", "$CDN_ZONE_URL/categories/index.html", "$CDN_ZONE_URL/archives/index.html", "$CDN_ZONE_URL/sitemap.xml", "$CDN_ZONE_URL/page-sitemap.xml", "$CDN_ZONE_URL/post-sitemap.xml", "$CDN_ZONE_URL/tag-sitemap.xml","$CDN_ZONE_URL/category-sitemap.xml"]}'

script:
  - npm run build
  - chmod u+x .travis/deploy.sh

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master

after_script:
  - git remote add Coding $CODING_REPO
  - git push Coding master
  - rsync -avz -e 'ssh -p 21521' ./public/ haochen@118.193.213.247:/home/haochen/site/root/cn/
