language: node_js

sudo: false

node_js:
  - "6"

cache:
  apt: true
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  ssh_known_hosts:
      - github.com
      - git.coding.net

before_script:
  - ssh-keyscan -H -t rsa,dsa git.coding.net >> ~/.ssh/known_hosts
  - ssh-keyscan -H -t rsa,dsa -p 21521 118.193.213.247 >> ~/.ssh/known_hosts
  - cat ~/.ssh/known_hosts

script:
  - npm run build
  - chmod u+x .travis/deploy.sh

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master

after_script:
  - git remote add Coding $CODING_REPO
  - git push Coding master
  - rsync -avz -e 'ssh -p 21521' ./public/ haochen@118.193.213.247:/home/haochen/site/cn/
